### PR TITLE
Added validators install to setup.py

### PR DESCRIPTION
**Pull request by sonofmun**

### CODE REVIEW

**Comment by PonteIneptique** [comment]
I would like to avoid this issue in the future.
Can we have our requirements like this : 

```txt
package
```

and our setup.py like this 

```python
with open(path.join(here, 'requirements.txt'), encoding='utf-8') as f:
    install_requires, tests_require = [], []
    now_we_have_dev = False
    for line in f:
        if line.startswith("#"):
             if "test" in line:
                   now_we_have_dev = True
        elif now_we_have_dev:
            tests_require.append(line.strip())
        else:
            install_requires.append(line.strip())

# ...
    install_requires=install_requires,
    tests_require=tests_require,
```
?

**Comment by PonteIneptique** [comment]
BTW, Not sure GitPython is required.

**Comment by sonofmun** [comment]
And then requirements.py would look like this?:

```
MyCapytain>=2.0.0
jingtrang==0.1.1
GitPython==2.1.0
requests>=2.8.1
prettytable==0.7.2
ansicolors==1.0.2
validators==0.12.2
#test
six>=1.10.0
mock==1.3.0
```

**Comment by PonteIneptique** [comment]
Yup

**Comment by sonofmun** [comment]
That works. Will add it here.

**Comment by PonteIneptique** [comment]
I'll let you merge and release ?

**Comment by sonofmun** [comment]
Will do.

**Pull request merged**
