### PR TITLE
 Changes to comply with MyCapytain 2.0.8

### PR DESCRIPTION
**Pull request by sonofmun**

### CODE REVIEW

**Comment by sonofmun** [comment]
Hold up. One more change coming.

**Comment by sonofmun** [comment]
Sorry, my bad. I want to add a test to make sure that capitains errors and empty reference errors are printed at the console. I should have waited with the PR.

**Comment by PonteIneptique** [comment]
I was too quick as well.
Should I release though ?

**Comment by sonofmun** [comment]
Release happens automatically.

**Comment by PonteIneptique** [comment]
Nope : only on new release on github. And I canceled travis build before it got done :D

**Comment by sonofmun** [comment]
I should be finished with the test in a few minutes. So better to wait with the release.

**Comment by PonteIneptique** [comment]
I'll probably still need you to make a 1.1.10 bump :/

**Comment by sonofmun** [comment]
Added the console tests and bumped to 1.1.10.

**Pull request merged**
