### PR TITLE
Removed the tar file from build

### PR DESCRIPTION
**Pull request by sonofmun**
This is no longer necessary since I have set up Travis to remove the failing files and so the two zip files created for the Github release will contain only the passing files

### CODE REVIEW

**Comment by sonofmun** [comment]
I think coverage decreased because I only commented out the function to create the tar file instead of removing it. It will be easy enough to recreate if we need it later so I will simply remove it.

**Comment by PonteIneptique** [comment]
Can you make it an option - - tar instead of removing it?

**Comment by sonofmun** [comment]
Will do.

**Comment by PonteIneptique** [comment]
Squash away !

**Comment by PonteIneptique** [comment]
Great.

**Pull request merged**
