### PR TITLE
Clean up test.run code.

### PR DESCRIPTION
**Pull request by rillian**
This is some cleanup of the code around the parallel iterators in Test.run I did while investigating #145.

The file lists returned by the finder are already iterable,
so there's no need to create a new list from them. If there
were just wrapping them in `list()` is another possiblity.

Also update the comments so they match the code better.

### CODE REVIEW

**Comment by PonteIneptique** [comment]
Dear @rillian , my complete appologies. I am in a deep tunnel regarding this. Maybe @sonofmun can chime in ?

**Comment by sonofmun** [comment]
I should have time to take a look at it later this week. Ping me again if you haven't heard anything by Thursday (June 20).

**Comment by rillian** [comment]
Ok. Thanks for the update!

**Comment by PonteIneptique** [comment]
Love the change in comments, definitely a good pr. Thanks !

**Comment by rillian** [comment]
\o/

**Pull request merged**
