### PR TITLE
Added plain text extraction to the build process

### PR DESCRIPTION
**Pull request by sonofmun**
You can see what the results would look like in the /text/ directory here: https://github.com/sonofmun/canonical-lat-test/tree/0.0.147

### CODE REVIEW

**Comment by PonteIneptique** [comment]
Few comments before I forget :
You should export the list of deepest node instead of the highest (aka the text) thus cleaning up any non text node. You'll still need tei note excluded. 

I would avoid using the resolver : il would simply look for xml file that are not __cts__. That will remove the need of parsing metadata. 

I'd prefer that as an option.

**Comment by sonofmun** [comment]
Would I get the deepest node by specifying the `subreference` in the `getTextualNode` method?
And I am not sure how I can export to plain text without either using the resolver or having to parse the file myself? In `interactive_text.export(Mimetypes.PLAINTEXT)`, `interactive_text` needs to be `MyCapytain.resources.texts.local.capitains.cts.__SimplePassage__`. And since this is part of the build script, I think I need to reload the collection in order to use CapiTainS to extract the textual nodes, thus the resolver. Is there a better way to do this, e.g., to carry `Repository` over from `hooktest` to `hooktest-build`? Or am I completely missing the point, somehow?

**Comment by PonteIneptique** [comment]
1. List all files that are not __cts__.xml
2. Initiate a `text = `[CapitainsCtsText](http://mycapytain.readthedocs.io/en/latest/MyCapytain.api.html#MyCapytain.resources.texts.local.capitains.cts.CapitainsCtsText)
3. Retrieve references : `reffs = text.getReffs(depth=len(text.citation))`
4. Retrieve passages : `passages = [text.getTextualNode(passage) for passage in reffs]`
5. Export passages to text.

**Comment by sonofmun** [comment]
Stupid. I used my local paths to load some files in the tests. That is why it failed. I will correct it and push the new version.

**Comment by sonofmun** [comment]
I need to test the exception on the plain_text function. Also, I think I need to specify the exception more closely. But I honestly don't remember what the error was that I was trying to catch.

**Comment by sonofmun** [comment]
I remember now. The exception I was getting was when using the resolver and there being a file mentioned in the metadata that didn't actually exist in the file system. I will remove the try, except statement and repush since I am no longer using the resolver.

**Comment by PonteIneptique** [comment]
All great and nearly ready to merge except : 

- [ ] Build class init documentation has not been updated
- [ ] CHANGES not updated
- [ ] Bump minor version (second number) because addition to the code base ;)

**Comment by PonteIneptique** [comment]
Hey !
I actually missed one last thing : could you add a section to the readme for this new "method" ? I don't see the build shown there :)

**Comment by sonofmun** [comment]
As I said in the text for the commit:

```
I didn't add very much since the scope at this point is fairly limited. I simply added it into the flow of prose for the `.travis.yml` file for now. Once I add the `txt`, `csv`, and `json` parameters, I will add a whole section for hooktest-build.
```

**Pull request merged**
