### PR TITLE
Added commentary to URN testing

### PR DESCRIPTION
**Pull request by sonofmun**

### CODE REVIEW

**Comment by PonteIneptique** [comment]
You missed 
https://github.com/Capitains/HookTest/blob/master/HookTest/capitains_units/cts.py#L588-L589

**Comment by sonofmun** [comment]
I got that in the other PR #88

**Comment by sonofmun** [comment]
You are a slave driver!

**Comment by PonteIneptique** [comment]
In setup.py, change the version to 1.0.1 and add a line in https://github.com/Capitains/HookTest/blob/master/CHANGES.txt which states your bugfixe and the version bump.
Then I'll merge and release to pypi :)

**Comment by sonofmun** [comment]
Should this be squashed?

**Comment by PonteIneptique** [comment]
Yes

**Comment by sonofmun** [comment]
I assume that was approval to squash and merge. But I will wait until you definitively say to squash to actually do it.

**Comment by PonteIneptique** [comment]
SQUASH AWAY !

2017-05-04 9:29 GMT+02:00 Matthew Munson <notifications@github.com>:

**Pull request merged**
