### PR TITLE
Fixed java options in Travis causing test failure

### PR DESCRIPTION
**Pull request by sonofmun**
Fix for #108

### CODE REVIEW

**Comment by PonteIneptique** [comment]
@sonofmun up to you !

**Comment by sonofmun** [comment]
I like the way you re-organized the code. There is still no test, however, for the case on Travis where they have a _JAVA_OPTIONS environment variable that prints either (most likely) to stdout or (less likely) to stderr. We can see that it works since the files now pass (e.g., https://travis-ci.org/sonofmun/canonical-lat-test/builds/277242587?utm_source=github_status&utm_medium=notification). But we are not testing whether this actually removes the lines that it is supposed to. Perhaps that is no big deal, I don't know. Just saying.

**Comment by PonteIneptique** [comment]
You're completely right. I think it could just be left as an issue for later, issue that would not need a new release, unlike the need for this quickfix

**Comment by sonofmun** [comment]
Good. I will add that to the issue description (#108) and merge this.

**Comment by sonofmun** [comment]
Ach, Mensch. No update of the CHANGES.txt or setup.py. I am not a very good administrator. Do you want to do that or should I?

**Comment by PonteIneptique** [comment]
I'd prefer that you do it ;)

**Pull request merged**
