### PR TITLE
Added long description type to setup.py

### PR DESCRIPTION
**Pull request by sonofmun**
#131

### CODE REVIEW

**Comment by PonteIneptique** [comment]
I don't think we should release yet, or shall we ?

**Comment by sonofmun** [comment]
I think it might be overkill. On the other hand, no one can read our documentation on PyPI right now.

**Comment by PonteIneptique** [comment]
Release early, release often ?

**Comment by sonofmun** [comment]
I don't understand what is happening with Travis right now. Only the test for Python 3.5 failed. The other two passed. And that happened before but only with Python 3.6.

**Comment by PonteIneptique** [comment]
Everything green on my hand ?

**Comment by PonteIneptique** [comment]
Oh. The push is broken.
Sure :D

**Comment by sonofmun** [comment]
The "push" failed on my end. Now, after I restarted it, it passes.

**Comment by sonofmun** [comment]
If you have no complaints, I will merge this now so that it will show up when we release because of the bad setup.py.

**Comment by PonteIneptique** [comment]
Sure

**Pull request merged**
